/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastrousuario;

/**
 *
 * @author marce
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
public class telausuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telausuario.class.getName());

    /**
     * Creates new form telausuario
     */
    public telausuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        txtidusuario = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnlimpar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();

        jTextField1.setText("Cadastro de Usuário");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastro Usuário  ");

        lblusuario.setText("id usuário:");

        lblnome.setText("nome:");

        lblemail.setText("email:");

        lblsenha.setText("senha:");

        txtidusuario.setEditable(false);
        txtidusuario.addActionListener(this::txtidusuarioActionPerformed);

        txtnome.addActionListener(this::txtnomeActionPerformed);

        txtemail.addActionListener(this::txtemailActionPerformed);

        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(this::btnlimparActionPerformed);

        btnalterar.setText("Alterar");
        btnalterar.addActionListener(this::btnalterarActionPerformed);

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(this::btnexcluirActionPerformed);

        btncadastrar.setText("Cadastrar");
        btncadastrar.addActionListener(this::btncadastrarActionPerformed);

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(this::btnconsultarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btncadastrar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtidusuario)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(txtemail))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnalterar)
                            .addComponent(lblnome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlimpar))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario)
                    .addComponent(txtidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpar)
                    .addComponent(btnexcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnalterar)
                    .addComponent(btnconsultar))
                .addGap(21, 21, 21)
                .addComponent(btncadastrar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtidusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidusuarioActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        String nome = txtnome.getText();
        String email = txtemail.getText();
       String senha = new String(txtSenha.getPassword());

if (nome.isEmpty() || email.isEmpty() || senha.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Preencha todos os campos!"
    );

    return;
}

String senhaHash = BCrypt.hashpw(
        senha,
        BCrypt.gensalt(12)
);

String sql = "INSERT INTO usuario (nome, email, senha) VALUES (?, ?, ?)";

try {

    Connection conexaoBanco = conexao.conectar();

    PreparedStatement comando =
            conexaoBanco.prepareStatement(sql);

    comando.setString(1, nome);
    comando.setString(2, email);
    comando.setString(3, senhaHash);

    comando.executeUpdate();

    JOptionPane.showMessageDialog(
            this,
            "Usuário cadastrado com sucesso!"
    );

    txtnome.setText("");
    txtemail.setText("");
    txtSenha.setText("");

    comando.close();
    conexaoBanco.close();

} catch (SQLException erro) {

    JOptionPane.showMessageDialog(
            this,
            "Erro ao cadastrar: " + erro.getMessage()
    );
}
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        
    String id = txtidusuario.getText();
    String nome = txtnome.getText();
    String email = txtemail.getText();
    String senha = new String(txtSenha.getPassword());

    if (id.isEmpty() || nome.isEmpty() || email.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione um usuário e preencha os campos!"
        );

        return;
    }

    try {

        Connection conexaoBanco = conexao.conectar();

        if (senha.isEmpty()) {

            String sql = "UPDATE usuario "
                    + "SET nome = ?, email = ? "
                    + "WHERE id_usuario = ?";

            PreparedStatement comando =
                    conexaoBanco.prepareStatement(sql);

            comando.setString(1, nome);
            comando.setString(2, email);
            comando.setInt(3, Integer.parseInt(id));

            comando.executeUpdate();

            comando.close();

        } else {

            String senhaHash = BCrypt.hashpw(
                    senha,
                    BCrypt.gensalt(12)
            );

            String sql = "UPDATE usuario "
                    + "SET nome = ?, email = ?, senha = ? "
                    + "WHERE id_usuario = ?";

            PreparedStatement comando =
                    conexaoBanco.prepareStatement(sql);

            comando.setString(1, nome);
            comando.setString(2, email);
            comando.setString(3, senhaHash);
            comando.setInt(4, Integer.parseInt(id));

            comando.executeUpdate();

            comando.close();
        }

        conexaoBanco.close();

        JOptionPane.showMessageDialog(
                this,
                "Usuário alterado com sucesso!"
        );

        

        txtidusuario.setText("");
        txtnome.setText("");
        txtemail.setText("");
        txtSenha.setText("");

    } catch (SQLException erro) {

        JOptionPane.showMessageDialog(
                this,
                "Erro ao alterar: " + erro.getMessage()
        );
    }

    }//GEN-LAST:event_btnalterarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
       

    String id = txtidusuario.getText();

    if (id.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione um usuário!"
        );

        return;
    }

    int resposta = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir este usuário?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {

        String sql = "DELETE FROM usuario WHERE id_usuario = ?";

        try {

            Connection conexaoBanco = conexao.conectar();

            PreparedStatement comando =
                    conexaoBanco.prepareStatement(sql);

            comando.setInt(
                    1,
                    Integer.parseInt(id)
            );

            comando.executeUpdate();

            comando.close();
            conexaoBanco.close();

            JOptionPane.showMessageDialog(
                    this,
                    "Usuário excluído com sucesso!"
            );

           

            txtidusuario.setText("");
            txtnome.setText("");
            txtemail.setText("");
            txtSenha.setText("");

        } catch (SQLException erro) {

            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao excluir: " + erro.getMessage()
            );
        }
    }

    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        

    txtidusuario.setText("");
    txtnome.setText("");
    txtemail.setText("");
    txtSenha.setText("");


    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
    

    String email = JOptionPane.showInputDialog(
            this,
            "Digite o e-mail do usuário:"
    );

    if (email == null || email.isEmpty()) {
        return;
    }

    String sql =
            "SELECT id_usuario, nome, email "
            + "FROM usuario "
            + "WHERE email = ?";

    try {

        Connection conexaoBanco = conexao.conectar();

        PreparedStatement comando =
                conexaoBanco.prepareStatement(sql);

        comando.setString(1, email);

        java.sql.ResultSet resultado =
                comando.executeQuery();

        if (resultado.next()) {

            int id = resultado.getInt("id_usuario");
            String nome = resultado.getString("nome");
            String emailBanco = resultado.getString("email");

            JOptionPane.showMessageDialog(
                    this,
                    "ID: " + id
                    + "\nNome: " + nome
                    + "\nEmail: " + emailBanco
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Usuário não encontrado!"
            );
        }

        resultado.close();
        comando.close();
        conexaoBanco.close();

    } catch (SQLException erro) {

        JOptionPane.showMessageDialog(
                this,
                "Erro ao consultar: " + erro.getMessage()
        );
    }
    
    }//GEN-LAST:event_btnconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telausuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidusuario;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables

}
